### ISSUE TITLE
Crash when Exporting Sketches

### ISSUE THREAD

**Issue by bcernic** [Jnesselr/fusion-360-total-exporter#28]
[2020_09_22_13_42.txt](https://github.com/Jnesselr/fusion-360-total-exporter/files/5263112/2020_09_22_13_42.txt)
![exporter error](https://user-images.githubusercontent.com/55109628/93918003-bb60af80-fcd9-11ea-9ed4-39d8fcab556c.png)

When exporting sketches as .dxf is enabled and there is a drawing in the folder being exported it crashes. The error message references 'AttributeError: 'NoneType' object has no attribute 'design'.

**Comment by digiTALker** [comment]
```
Failed:
Traceback (most recent call last):
  File "D:/fusion-360-total-exporter-master/fusion-360-total-exporter-master/Fusion 360 Total Export.py", line 325, in run
    total_export.run(context)
  File "D:/fusion-360-total-exporter-master/fusion-360-total-exporter-master/Fusion 360 Total Export.py", line 50, in run
    self._export_data(output_path)
  File "D:/fusion-360-total-exporter-master/fusion-360-total-exporter-master/Fusion 360 Total Export.py", line 105, in _export_data
    self._write_data_file(output_path, file)
  File "D:/fusion-360-total-exporter-master/fusion-360-total-exporter-master/Fusion 360 Total Export.py", line 165, in _write_data_file
    self._name(file.name) + "." + file.fileExtension
  File "D:/fusion-360-total-exporter-master/fusion-360-total-exporter-master/Fusion 360 Total Export.py", line 306, in _take
    os.makedirs(out_path, exist_ok=True)
  File "C:/Users/Надёжный/AppData/Local/Autodesk/webdeploy/production/50d1a2b00ac928c7781cbca6551e586a5384d498/Python/lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'C:/Backup  Fusion360\\Hub Denis Lukanov\\Project \\.f3d'
```
