### ISSUE TITLE
Failed: The selected folder is not accessible

### ISSUE THREAD

**Issue by kraegar** [Jnesselr/fusion-360-total-exporter#4]
![image](https://user-images.githubusercontent.com/7407731/93546720-6a476900-f931-11ea-9c7e-22041997d538.png)
![image](https://user-images.githubusercontent.com/7407731/93546727-6f0c1d00-f931-11ea-9845-8c766dea7756.png)

**Comment by Jnesselr** [comment]
This is like a 6 levels deep sub component so my best guess here is you're trampling over the 260 character file path limit in Windows. Try [this](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/) and see if you get the same error.

**Comment by Gnindit** [comment]
I got this as well but I have long paths enabled since before (Win10). I also sometimes get this when using save as in fusion but as just a brief warning from fusion and then all is ok again.
Would it be possible just to skip since now script has to start over again?
I can try to save directly to d:\ instead so I at least can shorten the local path.
Did not help with shorter local path.
![Error 2b](https://user-images.githubusercontent.com/17782127/93561714-ff278200-f984-11ea-8421-415710b130ec.jpg)

**Comment by Gnindit** [comment]
I deleted the one above and got further until next problem. I think it is problem with naming files with "*" (ASCII 42).
![image](https://user-images.githubusercontent.com/17782127/93616204-b5668800-f9d4-11ea-99e6-ffa387ff8acc.png)
The OSError: line is in Swedish and says something like Wrong syntax for file name, folder name or volume label.

**Comment by Jnesselr** [comment]
The only things common so far I have to go on are that you're both on windows, you're both writing to the D:\ drive, and this is writing to several levels deep. Updated guess is that somehow a parent folder doesn't get made and this fails here with this error.

**Comment by Gnindit** [comment]
Scanned path length and we are up to about 150 characters on the local drive. So not so close to 256. 

Maybe this is the problem?
You can name things the same but Fusion puts an ending on it to keep them separate. But the script strips the ending :x from it when making folders and then the folder already exists.
They seem to be copies of each other and linked somehow since the can be right clicked and then option to make independent is there. I have no idea if script handles this as only one download or multiple, or how it should be for it to work.

![image](https://user-images.githubusercontent.com/17782127/93645036-7865ba00-fa03-11ea-8c5f-c72fc7096824.png)

**Comment by MrTrick** [comment]
Same problem here, too.
(exact same stacktrace as others)
![image](https://user-images.githubusercontent.com/127012/93652726-66414700-fa16-11ea-91c5-2c39fd27769b.png)

A skip or resume option would be wonderful.
Even a "log successes to one file, errors to another", so that this tool can export all the normal files, and the few weird edge cases  can be exported manually.

**Comment by Tailslide** [comment]
FWIW, I was able to work around this by plugging in a USB3.1 drive and writing the files to that. Both the usb drive and my C drive were formatted NTFS and had similar path depth so no idea why this worked but I'm happy!  I had like 200 projects I had to export. Thanks so much for the script.

**Comment by Gnindit** [comment]
Ran it now with latest update that I think also replaces the ":". 

Path not found. But as you can see it is searching for "\\BF12 Mount X "\\
notice the space at the end of the folder name that its trying to find. Windows takes away trailing spaces when folders are made.
![image](https://user-images.githubusercontent.com/17782127/93661385-b42a6f00-fa57-11ea-9798-9ddbc1f411d7.png)



I can test but would be nice to test on specific design so I do not have to wait 30 min each time until it reaches the problem one.
![image](https://user-images.githubusercontent.com/17782127/93661455-361a9800-fa58-11ea-9d4b-f95064c9d240.png)

**Comment by 3d-gussner** [comment]
You can Enable Win23 long paths via Group Policy Editor. I will try this if the script fails again. Google for it.
Open Group Policy Editor (Press Windows Key and type gpedit.msc and hit Enter key.
Navigate to the following directory:  Local Computer Policy > Computer Configuration > Administrative Templates > System > Filesystem > NTFS.
Click Enable NTFS long paths option and enable it.

**Comment by Gnindit** [comment]
> You can Enable Win23 long paths via Group Policy Editor. I will try this if the script fails again. Google for it.
> Open Group Policy Editor (Press Windows Key and type gpedit.msc and hit Enter key.
> Navigate to the following directory: Local Computer Policy > Computer Configuration > Administrative Templates > System > Filesystem > NTFS.
> Click Enable NTFS long paths option and enable it.

Is that the same as enabling long path in registry?
Dator\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
LongPathsEnabled = 1
If so that is not the problem.
Also the path (at least locally) is around 150.

**Comment by 3d-gussner** [comment]
> > You can Enable Win23 long paths via Group Policy Editor. I will try this if the script fails again. Google for it.
> > Open Group Policy Editor (Press Windows Key and type gpedit.msc and hit Enter key.
> > Navigate to the following directory: Local Computer Policy > Computer Configuration > Administrative Templates > System > Filesystem > NTFS.
> > Click Enable NTFS long paths option and enable it.
> 
> Is that the same as enabling long path in registry?
> Dator\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
> LongPathsEnabled = 1
> If so that is not the problem.
> Also the path (at least locally) is around 150.

I guess yes. But not sure if a "windows update" will overwrite it, so I stick with the GP even this can be "fixed/updated" by Windows Update.

Running it now with these settings after 5 approaches ending up in the root of a drive and still failing.

I will update here my results.

**Comment by 3d-gussner** [comment]
And failed again even with "NTFS long paths option" enabled.
```
---------------------------
Fusion 360
---------------------------
Failed:
Traceback (most recent call last):
  File "D:/Data/Github/Fusion360/Total_exporter/master/Fusion 360 Total Export.py", line 217, in run
    total_export.run(context)
  File "D:/Data/Github/Fusion360/Total_exporter/master/Fusion 360 Total Export.py", line 69, in run
    self._write_data_file(output_path, file)
  File "D:/Data/Github/Fusion360/Total_exporter/master/Fusion 360 Total Export.py", line 125, in _write_data_file
    self._write_component(file_folder_path, design.rootComponent)
  File "D:/Data/Github/Fusion360/Total_exporter/master/Fusion 360 Total Export.py", line 151, in _write_component
    self._write_component(sub_path, sub_component)
  File "D:/Data/Github/Fusion360/Total_exporter/master/Fusion 360 Total Export.py", line 151, in _write_component
    self._write_component(sub_path, sub_component)
  File "D:/Data/Github/Fusion360/Total_exporter/master/Fusion 360 Total Export.py", line 151, in _write_component
    self._write_component(sub_path, sub_component)
  [Previous line repeated 2 more times]
  File "D:/Data/Github/Fusion360/Total_exporter/master/Fusion 360 Total Export.py", line 138, in _write_component
    self._write_stl(output_path, component)
  File "D:/Data/Github/Fusion360/Total_exporter/master/Fusion 360 Total Export.py", line 173, in _write_stl
    self._take(output_path)
  File "D:/Data/Github/Fusion360/Total_exporter/master/Fusion 360 Total Export.py", line 203, in _take
    os.makedirs(out_path, exist_ok=True)
  File "C:/Users/<username>/AppData/Local/Autodesk/webdeploy/production/<some numbers>/Python/lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 206] The filename or extension is too long: 'D:/Hub 3d Gussner\\Project 140100\\140100\\141001\\140100E3DMCLR600SQ.f3d\\140100E3DMCLR600SQ v4\\SSTTopassXYasE3DMCLR v26\\SSTTOPPLATE5DE3DMCLR v18\\SSTLangepillarNema23Z14E3DMCLR v5\\NEMA23 57BYGH627 v1\\pan head cross recess screwisoISO 7045  M3 x 30  Z  25C'

---------------------------
OK   
---------------------------
```

**Comment by 3d-gussner** [comment]
After renaming the "pan head cross recess screwisoISO 7045  M3 x 30  Z  25C" to something shorter without spaces the script could continue .... waiting what happens next

**Comment by Gnindit** [comment]
I have found this 
https://github.com/Jnesselr/fusion-360-total-exporter/pull/14#issuecomment-695201180

**Comment by 3d-gussner** [comment]
After long time working fine it crashed again... merged the Bozzzo changes and hope this will help.

**Comment by 3d-gussner** [comment]
Here some stats of my 1st project (still not finished):
- 4.8GB
- 12.765 Files
- 2.586 Folders

**Comment by 3d-gussner** [comment]
After doing well Fusion360 crashed! Restart ....
![image](https://user-images.githubusercontent.com/25530011/93668594-8fe98500-fa8d-11ea-9fbe-3a463fe9cd4a.png)

**Comment by 3d-gussner** [comment]
As a workaround not to start from the beginning I modified the script:
from `for project_index in range(all_projects.count):`
to `for project_index in range(5, all_projects.count):` 
Then it starts at project 6 instead running all previous finished.

**Comment by Gnindit** [comment]
This now seems to work for me
`def _name(self, name):`
`    return re.sub('[^a-zA-Z0-9 \n\.]', '', name).strip()`

**Comment by beer73** [comment]
Hello, I just want to confirm that the **workaround** proposed by @Tailslide to export to usb seems to work correctly for me. Nor can I find a technical explanation for it.
