### ISSUE TITLE
Error just after the export starts

### ISSUE THREAD

**Issue by vespassassina** [Jnesselr/fusion-360-total-exporter#44]
![image](https://user-images.githubusercontent.com/83391040/228830358-ba0ba6ac-ebae-4ce0-a9c9-f43c03d944be.png)

i am a free/hobby user

2023-03-30 14:01:44,166 - INFO - Starting export!
2023-03-30 14:01:44,399 - INFO - Exporting hub "Diego Trinciarelli"
2023-03-30 14:01:44,751 - INFO - Exporting project "3D Printers"
2023-03-30 14:01:46,667 - INFO - Exporting file "CalibrationCubeRack"
2023-03-30 14:01:47,548 - INFO - Writing to "C:/temp\Hub Diego Trinciarelli\Project 3D Printers\3D Printers\CalibrationCubeRack.f3d"
2023-03-30 14:01:47,674 - INFO - Writing component "CalibrationCubeRack v1" to "C:/temp\Hub Diego Trinciarelli\Project 3D Printers\3D Printers\CalibrationCubeRack.f3d"
2023-03-30 14:01:47,674 - INFO - Writing step file "C:/temp\Hub Diego Trinciarelli\Project 3D Printers\3D Printers\CalibrationCubeRack.f3d\CalibrationCubeRack v1.stp"
2023-03-30 14:01:48,049 - INFO - Writing stl file "C:/temp\Hub Diego Trinciarelli\Project 3D Printers\3D Printers\CalibrationCubeRack.f3d\CalibrationCubeRack v1.stl"
2023-03-30 14:01:48,356 - INFO - Writing stl body file "C:/temp\Hub Diego Trinciarelli\Project 3D Printers\3D Printers\CalibrationCubeRack.f3d\CalibrationCubeRack v1\Body1.stl"
2023-03-30 14:01:48,706 - INFO - Writing iges file "C:/temp\Hub Diego Trinciarelli\Project 3D Printers\3D Printers\CalibrationCubeRack.f3d\CalibrationCubeRack v1.igs"
2023-03-30 14:01:48,706 - ERROR - Failed while working on "CalibrationCubeRack"
Traceback (most recent call last):
  File "C:/Users/vespa/OneDrive/3DP/F360/fusion-360-total-exporter-master/Fusion 360 Total Export.py", line 184, in _write_data_file
    self._write_component(file_folder_path, design.rootComponent)
  File "C:/Users/vespa/OneDrive/3DP/F360/fusion-360-total-exporter-master/Fusion 360 Total Export.py", line 208, in _write_component
    self._write_iges(output_path, component)
  File "C:/Users/vespa/OneDrive/3DP/F360/fusion-360-total-exporter-master/Fusion 360 Total Export.py", line 292, in _write_iges
    export_manager.execute(options)
  File "C:\Users/vespa/AppData/Local/Autodesk/webdeploy/production/540c9578410bc15ff261605667cfced82aa9ac6d/Api/Python/packages\adsk\fusion.py", line 18885, in execute
    return _fusion.ExportManager_execute(self, exportOptions)
RuntimeError: 3 : Cannot execute the export operation to create the file in the format specified by the ExportOptions as the user is restricted.

**Comment by Whitehawk2000** [comment]
Same Error here. :-/

**Comment by theos10** [comment]
Same Error

**Comment by happymuffen** [comment]
+1

**Comment by JonyEpsilon** [comment]
Commenting out line 208, which tries to export in IGES format, by adding a `#` at the start like so

```
    # self._write_iges(output_path, component)
```

should fix it.

**Comment by theos10** [comment]
It Works fine, thank you.

**Comment by moriraaca** [comment]
@JonyEpsilon 's workaround works ok. The downside is IGES files won't be exported, but I think that's something that needs to be dealt with - it seems that IGES export has became a paid feature (I haven't seen it in release notes or anything, but when I try to manually export IGES option is disabled and there's a message at the bottom suggesting it's a paid feature.
![image](https://github.com/Jnesselr/fusion-360-total-exporter/assets/20703333/534a6b40-1c5d-444f-b2c7-91cda1a01c30)

Personally I don't see myself ever using solidworks so it's fine by me.

**Comment by Jnesselr** [comment]
I haven't had time to work on this, but please check out #46 and see if that works for you.
